// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5qLB-p5Hv11PWlm5vU_fpKg-eudEvZk',
    appId: '1:1027606650581:web:2c218289f4dc398dca8c5c',
    messagingSenderId: '1027606650581',
    projectId: 'royalapp-4ff56',
    authDomain: 'royalapp-4ff56.firebaseapp.com',
    storageBucket: 'royalapp-4ff56.appspot.com',
    measurementId: 'G-K1BH6BLCW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnlEvx_FkR5HklEUuKXnDEaRowtB4nZLA',
    appId: '1:1027606650581:android:8a064d464cb6b316ca8c5c',
    messagingSenderId: '1027606650581',
    projectId: 'royalapp-4ff56',
    storageBucket: 'royalapp-4ff56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANRxQno8hUvCFE-T-22eAgPhY8Nr2eACI',
    appId: '1:1027606650581:ios:0d74f0c0da1feed4ca8c5c',
    messagingSenderId: '1027606650581',
    projectId: 'royalapp-4ff56',
    storageBucket: 'royalapp-4ff56.appspot.com',
    iosBundleId: 'royal.app.royalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRxQno8hUvCFE-T-22eAgPhY8Nr2eACI',
    appId: '1:1027606650581:ios:0d74f0c0da1feed4ca8c5c',
    messagingSenderId: '1027606650581',
    projectId: 'royalapp-4ff56',
    storageBucket: 'royalapp-4ff56.appspot.com',
    iosBundleId: 'royal.app.royalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM5qLB-p5Hv11PWlm5vU_fpKg-eudEvZk',
    appId: '1:1027606650581:web:aa7c6a9dbda9e152ca8c5c',
    messagingSenderId: '1027606650581',
    projectId: 'royalapp-4ff56',
    authDomain: 'royalapp-4ff56.firebaseapp.com',
    storageBucket: 'royalapp-4ff56.appspot.com',
    measurementId: 'G-FLGFC53K0L',
  );
}
